### PR TITLE
Solution to NET 5 and nuget updates to latest

### PR DESCRIPTION
**Pull request by lenwen**
Solution to NET 5 and nuget Identity update to 5.0.1 mongodb to 2.11.5 and htmlagilitypack to 1.11.29

Before you add this.
Create branch 3.1 to support Net core 3 version.
And the master will be Net 5 support

### CODE REVIEW

**Comment by vova3211** [comment]
Will check it.
Thanks for your contribution!

**Review by vova3211 — APPROVED** [review]

**Comment by lenwen** [comment]
Do you  know how to merge it into master?

**Comment by vova3211** [comment]
I'll merge it asap.
Just need prepare docs update (readme etc.).

Also only Matteo can publish nuget package and he unavailable right now. Even after we merge it, it can take a while to have new package for NET 5.0

**Comment by przemo1983** [comment]
Can you please publish nuget package for NET 5.0?

**Comment by vova3211** [comment]
Sorry guys, was busy a lit bit. I'm planning to merge PR on this weekends.

Anyway, I don't have access to publish nuget package. So the best solution for you right now - fork/clone repository to your sln and use it as the project reference. Or use it as [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

**Comment by matteofabbri** [comment]
Im sorry to anybody but the pandemic has exterminated my family, crashed my marriage and flushed my whole live down the toilet.
So I don't have the time either the energy to take care of the package.
@vova3211 send me your email at me@matteofabbri.org so I can add you to nuget owners

**Comment by Ryanlewis2018** [comment]
Matteo I'm incredibly sorry to hear that. Thank you for assisting all your fellow devs and hope things get better. Time heals all wounds. 

> Im sorry to anybody but the pandemic has exterminated my family, crashed my marriage and flushed my whole live down the toilet.
> 
> So I don't have the time either the energy to take care of the package.
> 
> @vova3211 send me your email at me@matteofabbri.org so I can add you to nuget owners

**Pull request merged**
