### PR TITLE
Added .NET Core 3.1 and .NET 5 target frameworks

### PR DESCRIPTION
**Pull request by daviddesmet**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Project now targets .NET Core 3.1 and .NET 5 as an addition to .NET Standard 2.1

There's a vulnerability in `System.Text.Encodings.Web@4.5.0` introduced through `Microsoft.AspNetCore.Authentication@2.2.0` which is a reference used in `.NET Standard 2.1`. More info [here](https://github.com/dotnet/runtime/issues/49377).

This vulnerability throws a red flag when using automated vulnerability detection tools.

So targeting those frameworks fixes the issue and is a good way to provide existing functionality while moving forward.

Where has this been tested?
---------------------------
**Operating System:** Windows, Linux and macOS.

**.Net Core Version:** .NET 5 and .NET Core 3.1

Does this introduce a breaking change?
-----------------------------------------

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vova3211** [comment]
Hi @daviddesmet !
Thanks for your contribution!

2.2.x packages are out of support and are not receiving updates and even MS guys recommend to use 2.1 instead. I am thinking about downgrade nuget packages version to 2.1 for .Net Standard 2.1, and set separate version 3.1.x for .Net Core 3.1 and 5.0.x for .Net 5.0 accordingly.
What your thoughts about it?

**Comment by vova3211** [comment]
It will be smth like this:
```
<ItemGroup>
	<PackageReference Include="MongoDB.Driver" Version="2.11.6" />
</ItemGroup>

<ItemGroup Condition="$(TargetFramework) != 'netstandard2.1'">
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>

<ItemGroup Condition="$(TargetFramework) == 'netcoreapp3.1'">
	<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="3.1.18" />
	<PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="3.1.18" />
</ItemGroup>

<ItemGroup Condition="$(TargetFramework) == 'net5.0'">
	<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="5.0.9" />
	<PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="5.0.9" />
</ItemGroup>

<ItemGroup Condition="$(TargetFramework) == 'netstandard2.1'">
	<PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.1.2" />
	<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.1.2" />
	<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="2.1.6" />
	<PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="2.1.6" />
</ItemGroup>
```

**Comment by daviddesmet** [comment]
Hi @vova3211,

You are right about 2.2 but also 2.1 reached end-of-life on August 21, [source](https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

Nonetheless, targeting 2.1 would be better for the user base which haven't upgraded yet.

Regarding your suggestion, `Microsoft.Extensions.*` is not needed for .NET Core 3.1 and 5.0 since both have the Framework reference.

I've made the downgrade changes.

**Comment by daviddesmet** [comment]
Hi @vova3211 
I wonder if you had any chance to take a look at the updated PR?

Thanks

**Review by vova3211 — APPROVED** [review]

**Comment by vova3211** [comment]
was a bit busy 😅 

if you don't mind please check that rc package [8.3.0-rc](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.3.0-rc)

**Comment by daviddesmet** [comment]
@vova3211 

No worries, it happens to everyone.

I've just tested [8.3.0-rc](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/8.3.0-rc) and I'm happy to inform you that there's no more critical vulnerability alert since it now uses System.Text.Encodings.Web 5.0.1 on .NET 5.

Btw, any plans to upgrade the [MongoDB.Driver](https://mongodb.github.io/mongo-csharp-driver/2.13/what_is_new/) too?

Thanks

**Comment by vova3211** [comment]
yes, will update it 👍 

and again thanks for your contribution

**Pull request merged**
