### PR TITLE
Deep optimization of the User data structures.

### PR DESCRIPTION
**Pull request by DNemtsov**
This one is big;) I've been testing the library on big data sets, and realized the User entities are always downloaded and updated as a whole, thus dragging all the array fields with them.
TUser entity made lightweight and stripped of the array fields.
Its update workflows now rely on direct entity fields update w/o DB interaction because the Identity framework saves it in the end of each manipulation anyways.
The newly introduced MongoUserInfo is intended to store the growing array fields, which can become really big for large multi-tenant applications where each user can have multiple tenant-specific roles and big fine-grained claim sets.
TUserInfo type parameter allows to subclass the type to add user-specific fields that are upfront massive or can grow big.
MongoUserInfos are never to be downloaded as a whole document, but queried and manipulated incrementally thus saving network bandwidth, RAM, and providing optimal performance.

### CODE REVIEW

**Comment by vova3211** [comment]
Hi @DNemtsov! Thank for you great work. There are a lot of changes which need be tested before merging. I'll test it and a leave results in comment, so Matteo can check it and approve merge.

**Comment by matteofabbri** [comment]
WOW ! This is big i'm still looking at it, but a lot <3 
Sadly i did so many breaking changes in the past and many people were not happy of them, so maybe we should add a migration tool ?

**Comment by matteofabbri** [comment]
@DNemtsov what happened, why did you removed the PR ?

**Comment by DNemtsov** [comment]
I've realized the resulting data structures differ way too much from the existing model. I'm not sure if the changes can be adopted within the same library.

**Comment by vova3211** [comment]
Man this huge work can not be sent to the trash bin.
Of course, we need prepare very well for this new major (i guess) update. Test all functionality, create migration guide etc. So people can easy migrate to new version.

Everything possible)

**Comment by matteofabbri** [comment]
@DNemtsov the funny part is that was more or less the very original architecture.
And than is was abandoned because dont leverage on the document architecture means big bloat in small environment.
I was thinking about making two different libs, one "compact" and one "big" what are you opinions ? 
Meanwhile i made some test and found that one damn single class in Identity as int ad Id, just to mess up the life of people 

https://github.com/dotnet/aspnetcore/issues/21945

**Pull request closed without merging**
